name: CI
on: 
  push:
      branches: [workflow]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
         node-version: "18.x"
      - run: npm ci
      - run: npm test -- --coverage
        env: 
          CI: true
